#!/usr/bin/env sh

# 用法：
#   1. 将本文件复制到 .git/hooks/commit-msg
#   2. （非windows上）chmod a+x .git/hooks/commit-msg

msg=$(head -n1 "$1")
prefix_regex='^(feat|fix|docs|style|refactor|perf|test|chore|revert|build|ci)(\(.+\))?!?: .+|^Merge( .*)?$'

if ! printf '%s\n' "$msg" | grep -Eq "$prefix_regex"; then
  printf '提交信息必须符合 conventional commits 格式\n' >&2
  exit 1
fi
exit 0