export const loginName = 'login'
export const registerName = 'register'
export const userListName = 'userList'
export const userHistoriesName = 'userHistories'
export const userCreditName = 'userCredit'
export const aboutName = 'about'