export const mySavesName = 'mySaves'
export const searchSaveName = 'searchSave'
export const saveToolsName = 'saveTools'
export const saveDiffsName = 'saveDiffs'
export const saveFoldersName = 'saveFolders'